### ISSUE TITLE
Scope resolvers

### ISSUE THREAD

**Issue by rmeuth01** [CraigKnoblauch/keybox#5]
Drop scope resolvers throughout

**Comment by CraigKnoblauch** [comment]
Based on our conversation I'm dropping the scope resolvers in the library cpp files. 
Based on [this post](https://stackoverflow.com/questions/983310/calling-a-method-from-another-method-in-the-same-class-in-c) I don't need to do somehting like `this->function()` either.

**Comment by CraigKnoblauch** [comment]
Resolved by commit [945059e](https://github.com/CraigKnoblauch/keybox/commit/945059eaae7207fdc4c079e8997246a28e486620)
